version: '3.8'

services:
  frontend:
    image: your-dockerhub-username/app-front:v1.2.3  # OVO PROMENI u PRAVI tag
    ports:
      - "4200:80"
    environment:
      APIHOST: http://localhost:3000/api/
